import { Router, Request, Response, NextFunction } from 'express';

export class MyResponses {
    constructor() { }

    /**
        * 
        * @param res 
        * @param {*} data - success details generated by node or whatever third party or library is generating the result 
        * @param code - error code
        * @param [message] - extra information to be sent concerning the result
        */
    public sendSuccess(res: Response, data, code: Number, message: String = "", ) {
        let body = {
            error: false,
            data: data,
            code: code,
            message: message,
        }
        res.send(body)
    }


    /**
     * 
     * @param res 
     * @param {*} err - error details generated by node or whatever third party or library is getting the error 
     * @param code - error code
     * @param [message] - extra information to be sent concerning the error 
     */
    public sendError(res: Response, err, code: Number, message: String = "", ) {
        let body = {
            error: true,
            details: err,
            code: code,
            message: message,
        }
        res.send(body)
    }
}
